Drop column version from analytics_events
tinybirdco/use-case-examples pull request #347
Opened 2024-07-19 13:40 UTC by joscalv

2024-07-19 14:28 UTC, alrocar requested changes

2024-07-19 14:28 UTC, alrocar commented on drop_column/README.MD
> +** 'analytics_events' created
This is the output from CI

```
** Detecting changes from last commit ...
** Diffs from current commit '3afc8032b98c2f961e370fc1dda10b2a783fdc02' and new 'b0d520d2b0a2077326cd71a8111c7e6daa97048c':
	modified:	drop_column/datasources/analytics_events.datasource

** Preparing commit ...
** Processing ./datasources/analytics_events.datasource
** Building dependencies

** [DRY RUN] Deploying commit ...
** [DRY RUN] Running 'analytics_events' 

** Deploying commit ...
** Running 'analytics_events' 
** The description or schema of 'analytics_events' has changed.
**   -  DROP COLUMN `version`
** The Data Source has been correctly updated.
** 'analytics_events' created
** Not pushing fixtures
** New commit deployed: 'b0d520d2b0a2077[32](https://github.com/tinybirdco/use-case-examples/actions/runs/10009150300/job/27669046455?pr=347#step:12:33)6cd71a8111c7e6daa97048c'
```

2024-07-22 06:53 UTC, joscalv commented on drop_column/README.MD
> +** 'analytics_events' created
changed

2024-07-22 06:54 UTC, alrocar approved these changes

2024-07-22 06:56 UTC, merged